#!/bin/sh
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # #       EXECUTION ORDER       # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                   |                                      |                                    #
#   INSTALLATION                    |   UPGRADE                            |    UNINSTALLATION                  #
#                                   |                                      |                                    #
#      prereplace                   |      start-stop-status prestop       |      start-stop-status prestop     #
#      preinst                      |      start-stop-status stop          |      start-stop-status stop        #
#      postinst                     |      preupgrade                      |      preuninst                     #
#      postreplace                  |      preuninst                       |  ->  postuninst                    #
#      start-stop-status prestart   |      postuninst                      |                                    #
#      start-stop-status start      |      prereplace                      |                                    #
#                                   |      preinst                         |                                    #
#                                   |      postinst                        |                                    #
#   START                           |      postreplace                     |                                    #
#                                   |      postupgrade                     |                                    #
#      start-stop-status prestart   |      start-stop-status prestart      |                                    #
#      start-stop-status start      |      start-stop-status start         |                                    #
#                                   |                                      |                                    #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

#Remove RoonServer config file
ROON_ROOT="/var/packages/$SYNOPKG_PKGNAME"
[ -f "$ROON_ROOT/etc/RoonServer.ini" ] && rm "$ROON_ROOT/etc/RoonServer.ini"
exit 0